# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    tags:
      - "*"

jobs:
  build:

    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build
      run: pwsh ./build.ps1
    - name: Get Repo Name
      id: get_repo_name
      run: |
        repo_fullname="${{ github.repository }}"
        repo_name="${repo_fullname##*/}"
        echo "REPO_NAME=${repo_name}" >> $GITHUB_ENV
    - name: Get Tag Name
      id: get_tag_name
      run: |
        tag_name="${{ github.ref }}"
        tag_name="${tag_name#refs/tags/}"
        echo "TAG_NAME=${tag_name}" >> $GITHUB_ENV
    - name: Create Release
      run: |
        cd "./out/PowerbiUtils/"
        zip -r "../${REPO_NAME}_${TAG_NAME}.zip" "./"
    - name: Upload Release
      run: |
        gh release create ${TAG_NAME} "./out/${REPO_NAME}_${TAG_NAME}.zip"
      env:
        GH_TOKEN: ${{ github.token }}